### ISSUE TITLE
Récupérer les APIs des différents points d'apport / déchèterie 

### ISSUE THREAD

**Issue by Clem-mrtn** [incubateur-ademe/quefairedemesdechets#15]
- [ ] Relancer nos contacts pour avoir accès aux API 
- [ ] Test
- [ ] Plugguer au simulateur QFDMD

**Comment by martinregner** [comment]
Retour de OCAD3E : préciser les besoins pour l'API @florianpanchout 

Relance à faire des autres filières

**Comment by florianpanchout** [comment]
J'ai intégré les points d'apport OCAD3E. 

(J'ai créé cette issue pour les retours spécifique à la map : #24)

**Comment by florianpanchout** [comment]
J'ai fait un peu d'exploration dans le code de l'ancienne version (oui j'ai des hobbies chelou) : 

Il y a 4 calls différents pour les points d'apport, déterminé par le paramètre "Bdd" du déchet : 

- **ademe** : Va chercher dans les points d'apports rentrés dans le back office (Il n'y en a aucun)
- **ocad3e** : Va chercher dans la base OCAD3E que l'on vient d'intégrer
- **google** : Va chercher les pharmacies via Google (Il n'y a que le déchet "medicamment" qui est concerné)
- **sinoe** : Va chercher dans la base sinoe (sur le site http://www.sinoe.org, pas sur la version koumoul). Il n'y a aucun déchet attribué à cette base

Tout ça pour dire que l'on a déjà plus de point d'apport que l'ancienne version (puisque l'on gère les déchèteries et eux non). Si personne d'autres ne réponds maintenant, c'est probablement parce qu'il n'y a rien d'autre.

**Comment by martinregner** [comment]
> _Légende :_
> - [x] _Intégré_
> - [ ] _Non intégré_

Ont répondu : 
- [x] OCAD3E
- [X] Cyclamed
- [ ] Dastri : QFDMD renvoie pour l'instant aux pharmacies ; a renvoyé la procédure d'accès à l'API : [LISTE PDC DASTRI - Interface v1.2.pdf](https://github.com/datagir/quefairedemesdechets/files/7317720/LISTE.PDC.DASTRI.-.Interface.v1.2.pdf)
- [ ] APER La plaisance / Bâteau de plaisance --> **déchets inexistant à ce stade dans QFDMD** ; pas d'API : [Adresses centres de déconstruction APER.docx](https://github.com/datagir/quefairedemesdechets/files/7311357/Adresses.centres.de.deconstruction.APER.docx) ; https://www.recyclermonbateau.fr/
- [ ] Soren / Photovoltaïque --> **déchets inexistant à ce stade dans QFDMD** ; pas d'API : [Soren - Points d'apport volontaire 01-09-2021.xlsx](https://github.com/datagir/quefairedemesdechets/files/7317674/Soren.-.Points.d.apport.volontaire.01-09-2021.xlsx)
- [ ] Ecosystem / Petits Appareils Extincteurs (PAE) : pas d'API possible mais fichier OK : _En attente d'envoi._
- [ ] Ecomobilier / mobilier, oreiller, couette, matelas : échange téléphonique avec le nouveau DSI. API attendue en février 2022. Possibilité de la beta tester. Reviens vers nous lorsque ce sera possible.
- [ ] APER Pyro / Feu et fumigène ; message d'accusé réception de la demande et d'instruction ; pas de retour API ou fichier ; les points d'apport sont consultables ici : https://www.aper-pyro.fr/les-points-de-collecte/

Autres retours : 
- [ ] VHU : export Syderep possible ; connexion API ?

Réponse mais hors périmètre QFDMD : 
- Valdelia / Mobilier pro
