### ISSUE TITLE
Backoffice Koumoul

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/quefairedemesdechets#22]
Le jeu de donnée n'est pas en accès libre pour l'instant. Je ne peux donc pas le récupérer via l'app

**Comment by martinregner** [comment]
@florianpanchout c'est fait : 
- https://data.ademe.fr/datasets/que-faire-de-mes-dechets-liens
- https://data.ademe.fr/datasets/que-faire-de-mes-dechets-produits

**Comment by florianpanchout** [comment]
Le site prends maintenant les infos directement de Koumoul 

Par contre le site est statique. Donc le contenu des pages est généré à chaque build (à chaque fois que je change quelque chose dans le code, le site upload sur Netlify, va chercher les infos chez Koumoul et crée des pages html statiques avec).

Donc si l'on change quelque chose chez Koumoul, le site ne sait pas qu'il y a de nouvelles infos et ne rebuild pas. 

Il faut que Koumoul ajoute un hook qui fait qu'à chaque édition de leurs jeux de données (liens et produits), ils appellent cet endpoint en POST : ```https://api.netlify.com/build_hooks/615189df8b8ed42b27ae36d7``` qui va lancer un nouveau build du site.

**Comment by martinregner** [comment]
> Il faut que Koumoul ajoute un hook qui fait qu'à chaque édition de leurs jeux de données (liens et produits), ils appellent cet endpoint en POST : https://api.netlify.com/build_hooks/615189df8b8ed42b27ae36d7 qui va lancer un nouveau build du site.

@florianpanchout pour être sûr de lui emander la bonne chose, est-ce que tu peux voir directement avec Nicolas ?

**Comment by florianpanchout** [comment]
Réponse de Nicolas :  

> Nous n'avons pour l'instant pas de webhook au niveau d'un jeu de données, ils sont uniquement communs à tous les datasets.
Nous avançons en ce moment sur la partie notifications, ça pourrait s'en rapprocher.

Donc il faudra le faire à la main pour l'instant :(

**Comment by martinregner** [comment]
@florianpanchout j'en ai parlé avec Laurent. Il propose comme alternative en attendant d'automatiser 1 import Koumoul + rebuilt par mois (ou autre fréquence). C'est automatisé comme ça au pire ça se fait au prochain rebuilt.
Qu'en penses-tu ?

**Comment by florianpanchout** [comment]
Donc plutôt que d'automatiser à chaque import, il automatiserait chaque mois ? J'ai du mal à voir en quoi c'est plus simple pour lui aha

**Comment by florianpanchout** [comment]
Proposition alternative : Recoder un backoffice

Avantage : 
- On se passe de l'ancien back-office
- On se passe de koumoul

Désavantage : 
- Il faut le faire (1 à 4 jours de taf, selon que l'on fasse un vrai bo ou juste des fichiers markdown dans Github)

**Comment by martinregner** [comment]
Retour de Koumoul :

> Nous avons créé 2 nouveaux jeux de données temporaires pour faire les tests. Ces jeux de données ont la particularité de pouvoir être édités par formulaire, ligne par ligne, plutôt qu'en rechargeant un fichier qui contient toutes les données. Nous avons créé une page sur le portail interne de l'Ademe de notre plateforme qui présente 2 formulaires (un dans chaque onglet) pour éditer les 2 jeux de données produits et liens. Nous avons réimporté les données dans ces 2 jeux, mais les produits ne sont pas dans les liens (mais cela ne devrait pas empêcher de tester).
> 
> Si cela vous convient, nous ferons ensuite la bascule en supprimant et recréant les jeux de données actuellement disponibles en opendata (en refaisant correctement les liens avec les produits). Si mes explications ne sont pas très claires, je reste disponible pour répondre à d'éventuelles questions.
> 
> @Florian : la structure des jeux de données de test change un peu : nous avons "corrigé" une coquille liée à un mauvais encodage de caractère dans le nom d'un champ de chaque jeu de données, et le jeu de données "liens" ne fait plus référence à un libellé de produit mais à un identifiant. Est ce qu'on peut faire des modifications sur les autres champs (comme par exemple retirer les points d'interrogation des ids) ? Sinon les 2 jeux de données de tests sont accessibles ici :
>  * https://ademe.koumoul.com/datasets/que-faire-de-mes-dechets-liens-2
>  * https://ademe.koumoul.com/datasets/que-faire-de-mes-dechets-produits-2
>

**Comment by Clem-mrtn** [comment]
Dans mon souvenir la balle était dans leur camps : est-ce qu'on les relance pour voir s'ils ont bien matché l'ancien jeu de données avec le nouveau ?

**Comment by florianpanchout** [comment]
Tout est fait des deux côtés

**Comment by martinregner** [comment]
J'ai fait une modif sur les [meubles ](https://quefairedemesdechets.fr/dechet/meuble/) (correction d'une coquille : "Se le meuble... --> Si le meuble...") il y a environ 1h : c'est à jour côté Koumoul mais pas en ligne dans le simulateur... 🤔 
Encore un peu d'attente pour la synchro ? Ca se fait à un moment donné de la journée ?

**Comment by florianpanchout** [comment]
Ah oui ce ticket traitait de deux points. Le backoffice est maintenant en place. Par contre le site ne se rebuild pas automatiquement lorsque l'on modifie le jeu de données (voir https://github.com/datagir/quefairedemesdechets/issues/22#issuecomment-927897057).

Il faut que je le fasse à la main à chaque fois jusqu'à ce qu'ils implémentent l'appel chez eux :/

**Comment by martinregner** [comment]
OK merci pour le rappel.
Possible de programmer un rebuilt chaque mois ? (ex. le 1er du mois)

**Comment by florianpanchout** [comment]
@martinregner J'ai ajouté une page pour lancer un rebuild : https://quefairedemesdechets.fr/build

pw : `bidoubidou`

Comme ça il n'y a pas à attendre 1 mois pour voir ses modifications. Ça me semble mieux non ?

**Comment by martinregner** [comment]
Ah oui super ! 👍 
On parle du choix de pw ou pas ? ;)

**Comment by florianpanchout** [comment]
Aha je suis développeur front, pas expert sécurité

**Comment by florianpanchout** [comment]
Nouveau pw : `qfdmd`

**Comment by martinregner** [comment]
@florianpanchout : l'option "Notification" est désormais active sur data.ademe.fr

Si ça marche on pourra se passer du ~~`bidoubidou`~~ `pswrd` ! :)

**Comment by florianpanchout** [comment]
Réponse de Nicolas : "Non, le système de notifications ne peut pas exécuter d'appel POST."
