### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/quefairedemesdechets#26]
![Capture d’écran du 2021-09-20 11-40-47](https://user-images.githubusercontent.com/1177762/133982646-21bc2dd5-7142-47be-bfdd-6ab02cfa82ee.png)

**Comment by martinregner** [comment]
Pris en compte.
La modif apparaîtra au prochain import de données

**Comment by florianpanchout** [comment]
En vrai il y a plein de fautes partout. Est ce que ça ne vaudrait pas le coup de les extraire, de les passer dans un correcteur automatique, puis de les remettre dans Koumoul ?

**Comment by Clem-mrtn** [comment]
Ca peut être une bonne idée avant de faire le prochain import de données ? 
Après on peut quand même le faire en parallèle de la sortie du simulateur

**Comment by florianpanchout** [comment]
Oui ça peut être fait à n'importe quel moment

(pour être honnête, je suis un peu moins stressé par la sortie de QFDMD depuis que je sais qu'il s'agit de 40 visites quotidiennes...)

**Comment by martinregner** [comment]
C'est 50 à 160 par jour @florianpanchout  ! ;)

Et de grosses campagnes de com à venir 👍 

Pour bien faire pour le moment, il faut corriger dans l'ancien backoffice (toujours utilisé par Marilyne) pour pas se récupérer les fautes au prochain export...
https://github.com/datagir/quefairedemesdechets/issues/16 doit justement permettre de corriger directement dans Koumoul... si possible, ou de trouver une nouvelle façon de rentrer / mettre à jour les données.

**Comment by florianpanchout** [comment]
Ça pose un autre problème : 

@martinregner Tu as ajouté 2 propriété `dechéterie` et `pharmacie` dans les data Koumoul. Ces propriétés vont disparaitre au prochain export non ?

La solution que je peux voir serait d'utiliser le champs `Bdd` (Base de donnée dans le backoffice) pour signifier ces propriétés. Mettre Sinoe pour tous les déchets qui vont à la déchèterie. Et Google pour tous les déchets qui vont à la pharmacie. Le problème de cette méthode c'est qu'il n'est plus possible d'avoir différents types de point d'apport pour un même déchet (mais je ne sais pas si c'est grave)

**Comment by martinregner** [comment]
Pardon je n'avais pas vu ce message avant.
J'ai bien utilisé `Bdd` pour `dechéterie` mais pas `pharmacie`. Ca semble marcher encore non @florianpanchout ?

**Comment by florianpanchout** [comment]
Yes maintenant je prends `Bdd: google` pour savoir quand afficher les pharmacies (comme le site existant)

**Comment by Clem-mrtn** [comment]
#22
