### ISSUE TITLE
Personnaliser les suggestions de déchets proposées dans l'iframe

### ISSUE THREAD

**Issue by martinregner** [incubateur-ademe/quefairedemesdechets#32]
**P1** : en dur dans le paramétrage de l'iframe (pour le MTE)

- https://quefairedemesdechets.netlify.app/dechet/jouet-(non-electronique)
- https://quefairedemesdechets.netlify.app/dechet/velo-(hors-velo-electrique)
- https://quefairedemesdechets.netlify.app/dechet/vaisselle
- https://quefairedemesdechets.netlify.app/dechet/fourniture-scolaire-ou-de-bureau
- https://quefairedemesdechets.netlify.app/dechet/platre
- https://quefairedemesdechets.netlify.app/dechet/epluchures

P2 : réaliser un sélecteur (recherche dans la base) dans le panneau d’embed

**Comment by Clem-mrtn** [comment]
Du coup rendre _l'iframe_ personnalisable pour "n'importe quel acteur plutôt que de créer des suggestions spéciales MTE

**Comment by florianpanchout** [comment]
Le code maintenant que la prod est en ligne : 
```
 <script
    id="datagir_dechets"
    src="https://quefairedemesdechets.fr/iframe.js"
    data-search="?theme=default&suggestions=194,358,355,164,271,144"
></script>
```

**Comment by jdbaculard-ap** [comment]
> 



> Le code maintenant que c'est en prod :
> 
> ```
>  <script
>     id="datagir_dechets"
>     src="https://quefairedemesdechets.fr/iframe.js"
>     data-search="?theme=default&suggestions=194,358,355,164,271,144"
> ></script>
> ```

Bonjour

Puis-je avoir la liste complète des codes de suggestions ?
Ex : Equipement de piscine
Merci d'avance

**Comment by jdbaculard-ap** [comment]
Merci

De : Florian ***@***.***>
Date : jeudi, 22 septembre 2022 à 14:29
À : datagir/quefairedemesdechets ***@***.***>
Cc : jdbaculard-ap ***@***.***>, Comment ***@***.***>
Objet : Re: [datagir/quefairedemesdechets] Personnaliser les suggestions de déchets proposées dans l'iframe (#32)

Bonjour,

Vous pouvez voir la liste de l'ensemble des déchets ici : https://data.ademe.fr/datasets/que-faire-de-mes-dechets-produits (il faut cliquer sur le picto tableau à gauche).

Les codes de suggestions sont les mêmes que les id du tableau. Par exemple pour équipement de piscine, le code serait 369
